name: Workflow
on:  # yamllint disable-line rule:truthy
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unit-test:
    name: Run unit tests and check package coverage
    uses: dell/common-github-actions/.github/workflows/go-code-tester@add-code-tester

  security:
    name: Run gosec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Run gosec to check for security vulnerabilities
        uses: dell/common-github-actions/gosec-runner@main
        with:
          directories: "./..."
