name: Common Workflows
on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

jobs:

  # golang static analysis checks
  go-static-analysis:
    uses: KshitijaKakde/common-github-actions/.github/workflows/go-static-analysis.yaml@main
    name: Golang Validation

  # checks unit tests, package coverage, and gosec
  common:
    name: Run gosec, unit tests, and check package coverage
    uses: KshitijaKakde/common-github-actions/.github/workflows/go-common.yml@main
