name: Create Tag and Release

on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
    inputs:
      option:
        description: 'Select version to release'
        required: true
        type: choice
        default: 'minor'
        options:
          - major
          - minor
          - patch
          - n-1/n-2 patch (Provide input in the below box)
      version:
        description: "Patch version to release. example: 2.1.x (Use this only if n-1/n-2 patch is selected)"
        required: false
        type: string
  repository_dispatch:
    types: [auto-release-workflow]

jobs:
  process-inputs:
    name: Process Inputs
    runs-on: ubuntu-latest
    outputs:
      processedVersion: ${{ steps.set-version.outputs.versionEnv }}
    steps:
      - name: Process input
        id: set-version
        shell: bash
        run: |
          echo "Triggered by: ${{ github.event_name }}"
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "versionEnv=minor" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [[ "${{ github.event.inputs.version }}" != "" && "${{ github.event.inputs.option }}" == "n-1/n-2 patch (Provide input in the below box)" ]]; then
            echo "versionEnv=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [[ "${{ github.event.inputs.option }}" != "n-1/n-2 patch (Provide input in the below box)" ]]; then
            echo "versionEnv=${{ github.event.inputs.option }}" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "versionEnv=minor" >> $GITHUB_OUTPUT

  decrypt-secret:
    name: Decrypt Secret File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import GPG private key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Decrypt secret file
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" \
          --output secret.txt secret.txt.gpg
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

  csm-release:
    needs: [process-inputs, decrypt-secret]
    uses: KshitijaKakde/common-github-actions/.github/workflows/create-tag-release.yaml@main
    name: Release CSM Drivers and Modules
    with:
      version: ${{ needs.process-inputs.outputs.processedVersion }}
      images: 'csi-vxflexos'
    secrets: inherit
