# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# This workflow triggers a Jenkins job from GitHub Actions
name: Trigger Jenkins Job

on:
  workflow_dispatch:
    inputs:
      build_params:
        description: "Optional build parameters in query string format (e.g., param1=value1&param2=value2)"
        required: false
        type: string

jobs:
  trigger:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Jenkins Job via API
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_JOB_PATH: ${{ secrets.JENKINS_JOB_PATH }}
        run: |
          PARAMS="${{ inputs.build_params }}"

          if [ -z "$PARAMS" ]; then
            curl -X POST "$JENKINS_URL/$JENKINS_JOB_PATH/build" \
              --user "$JENKINS_USER:$JENKINS_TOKEN"
          else
            curl -X POST "$JENKINS_URL/$JENKINS_JOB_PATH/buildWithParameters?$PARAMS" \
              --user "$JENKINS_USER:$JENKINS_TOKEN"
          fi

      - name: Notify Trigger Status
        run: |
          echo "✅ Jenkins job '$JENKINS_JOB_PATH' has been triggered successfully."
          echo "🔍 Monitor the job at: $JENKINS_URL/$JENKINS_JOB_PATH"
          echo "📦 Parameters sent: '${{ inputs.build_params }}'"
          echo "🚀 Triggered by GitHub Actions workflow: ${{ github.workflow }}"
